/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OfertasecretaRouteImport } from './routes/ofertasecreta'
import { Route as IndexRouteImport } from './routes/index'

const OfertasecretaRoute = OfertasecretaRouteImport.update({
  id: '/ofertasecreta',
  path: '/ofertasecreta',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ofertasecreta': typeof OfertasecretaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ofertasecreta': typeof OfertasecretaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ofertasecreta': typeof OfertasecretaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ofertasecreta'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ofertasecreta'
  id: '__root__' | '/' | '/ofertasecreta'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OfertasecretaRoute: typeof OfertasecretaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ofertasecreta': {
      id: '/ofertasecreta'
      path: '/ofertasecreta'
      fullPath: '/ofertasecreta'
      preLoaderRoute: typeof OfertasecretaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OfertasecretaRoute: OfertasecretaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
